geodjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('world.urls')),
]

world/urls.py
from django.urls import path

from .views import IndexView, ProjectView, ReviewDetialView

app_name = 'world'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('project/<int:pk>/', ProjectView.as_view(), name='project'),
    path('review/<int:pk>/', ReviewDetialView.as_view(), name='review'),
]

world/models.py
from django.db import models
from django.utils import timezone


# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=10)
    phone = models.CharField(max_length=20, blank=True)
    email = models.EmailField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '联系人'


class ConstructionUnit(models.Model):
    corp_name = models.CharField(max_length=200, null=False, unique=True)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    introduction = models.TextField(max_length=500)

    def __str__(self):
        return self.corp_name

    class Meta:
        verbose_name = '建设单位'


class DesignInstitute(models.Model):
    corp_name = models.CharField(max_length=200, null=False, unique=True)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    introduction = models.TextField(max_length=500)

    def __str__(self):
        return self.corp_name

    class Meta:
        verbose_name = '设计院'


class Address(models.Model):
    region = models.CharField(max_length=15)
    road = models.CharField(max_length=15)
    boundaries = models.TextField(max_length=300)

    def __str__(self):
        return self.region + ' ' + self.road

    class Meta:
        verbose_name = '地址'


class Department(models.Model):
    name = models.CharField(max_length=50, unique=True, null=False)
    section = models.CharField(max_length=15)

    def __str__(self):
        return (self.name + ': ' + self.section)

    class Meta:
        verbose_name = '部门'


class Staff(models.Model):
    name = models.CharField(max_length=10)
    phone = models.CharField(max_length=20, blank=True)
    email = models.EmailField()
    section = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '部门参会人员'


class Expert(models.Model):
    name = models.CharField(max_length=10)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    section = models.CharField(max_length=50)
    title = models.CharField(max_length=15)
    intro = models.TextField(max_length=500)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '专家'


class ExpertReview(models.Model):
    review_data = models.DateField()
    experts = models.ManyToManyField(
        Expert,
        through='ReviewCom'
    )
    staffs = models.ManyToManyField(Staff)

    def __str__(self):
        return str(self.review_data) + '专家评审会'

    class Meta:
        verbose_name = '专家评审会'


class ReviewCom(models.Model):
    expert = models.ForeignKey(Expert, on_delete=models.CASCADE)
    review = models.ForeignKey(ExpertReview, on_delete=models.CASCADE)
    is_leader = models.BooleanField(default=False)

    def __str__(self):
        return str(self.review.review_data) + '专家评审会专家组成员'

    class Meta:
        verbose_name = '专家组成员'


class Commission(models.Model):
    com_date = models.DateField()
    session = models.IntegerField(verbose_name='规委会期数')
    notes = models.TextField('会议纪要', max_length=1000)
    grade = models.CharField('市级or 管委会？', max_length=15)

    def __str__(self):
        return str(self.com_date) + self.grade + '规委会'

    class Meta:
        verbose_name = '规委会'
        ordering = [
            '-com_date',
        ]


class Project(models.Model):
    name = models.CharField(max_length=50)
    apply_date = models.DateField(default=timezone.now)
    construction_unit = models.ForeignKey(ConstructionUnit, on_delete=models.CASCADE)
    institute = models.ForeignKey(DesignInstitute, on_delete=models.CASCADE)
    review = models.ForeignKey(ExpertReview, on_delete=models.CASCADE)
    commission = models.ForeignKey(Commission, on_delete=models.CASCADE)
    intro = models.TextField(max_length=500)
    addr = models.ForeignKey(Address, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '项目'
        ordering = [
            '-apply_date',
        ]

world/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Project, ExpertReview

# Create your views here.

class IndexView(ListView):
    model = Project
    template_name = 'index.html'


class ProjectView(DetailView):
    queryset = Project.objects.all()
    context_object_name = 'project'
    template_name = 'project.html'

class ReviewDetialView(DetailView):
    queryset = ExpertReview.objects.all()
    context_object_name = 'review'
    template_name = 'review.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['project_list'] = Project.objects.filter(review=self.object)
        return context

world/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>
    规划管理系统-
        {% block title %}

        {% endblock %}
    </title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'world:index' %}">首页</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'world:index' %}">项目 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
  {% block content %}
  <h1>Hello, world!</h1>
  {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

world/templates/index.html
{% extends "base.html" %}
{% block title %}
    首页
{% endblock %}

{% block content %}

    <div class="page-header">
        <h1>中关村高科技园区项目</h1>
    </div>

    {% for p in object_list %}
        <div class="list-group">
        <a href="{% url 'world:project' p.id %}" class="list-group-item list-group-item-action">{{ p.name }}</a>
        </div>
    {% endfor %}


{% endblock %}

world/templates/project.html
{% extends "base.html" %}
{% block title %}
    {{ project.name }}
{% endblock %}

{% block content %}

    <div class="jumbotron">
        <h1 class="display-4">{{ project.name }} </h1>
        <p class="lead">{{ project.intro }}</p>
        <hr class="my-4">
        <a href="{% url 'world:review' project.review.id %} ">{{ project.review }}</a>
        <p>{{ project.review }}</p>
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <a class="btn btn-lg" href="#" role="button">Learn more</a>
    </div>





{% endblock %}

world/templates/review.html
{% extends "base.html" %}
{% block title %}
    {{ review.name }}
{% endblock %}

{% block content %}

    <div class="jumbotron">
        <h1 class="display-4">{{ review }} </h1>
        <p class="lead">{{ review.review_data }}</p>
        <hr class="my-4">
        <ul class="list-group">
        <h2>专家</h2>
            {% for exp in review.experts.all %}
                <li class="list-group-item">{{ exp.name }}

                </li>
            {% endfor %}
        <h2>部门参会</h2>
        {% for staff in review.staffs.all %}
                <li class="list-group-item">{{ staff.name }}

                </li>
            {% endfor %}
<h2>项目</h2>
        {% for p in project_list %}
                <a href="{% url 'world:project' p.id %}" class="list-group-item list-group-item-action">{{ p.name }}</a>
            {% endfor %}

        </ul>
    <h2>会议意见</h2>
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <a class="btn btn-lg" href="#" role="button">Learn more</a>
    </div>





{% endblock %}